import type { LeadershipInsightDto } from '../rmApi';

interface InsightsPanelProps {
  insights: LeadershipInsightDto[];
}

/**
 * Leadership Insights panel (spec FR-58, PRD 15.2, T-035): the generated one-liners (top performing
 * broker, underperforming RM, turnaround at risk, follow-up compliance, largest premium opportunity),
 * each an icon glyph in a tinted halo plus a headline and supporting narrative. Content is
 * server-generated by `LeadershipInsightRules`, so this panel is purely presentational.
 */
function InsightsPanel({ insights }: InsightsPanelProps) {
  return (
    <div className="qiq-card" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--qiq-space-3)' }}>
      <div className="qiq-card-head" style={{ marginBottom: 0, alignItems: 'center' }}>
        <span className="qiq-card-title">Leadership Insights</span>
      </div>

      <ul
        data-testid="leadership-insights"
        style={{ listStyle: 'none', margin: 0, padding: 0, display: 'flex', flexDirection: 'column', gap: 'var(--qiq-space-3)' }}
      >
        {insights.length === 0 && <li className="qiq-card-sub">No insights available for this period.</li>}
        {insights.map((insight) => (
          <li
            key={insight.type}
            data-testid="insight-item"
            data-insight-type={insight.type}
            style={{ display: 'flex', alignItems: 'flex-start', gap: 'var(--qiq-space-3)' }}
          >
            <span aria-hidden="true" className="qiq-kpi-halo">
              {insight.icon}
            </span>
            <span style={{ display: 'flex', flexDirection: 'column', gap: 'var(--qiq-space-1)' }}>
              <span className="qiq-kpi-label" style={{ fontWeight: 600 }}>
                {insight.headline}
              </span>
              <span className="qiq-card-sub">{insight.narrative}</span>
            </span>
          </li>
        ))}
      </ul>
    </div>
  );
}

export default InsightsPanel;
